### PR TITLE
Monotone polygon 

### PR DESCRIPTION
**Pull request by obayomy**
Functionality Todo List:
- [x]  Add a function that checks whether entered points form a y-monotone polygon, return the paths if true
- [x] Add a function that takes number of points and arrange them into a y-monotone polygon
- [x] Make monotone generation generic for any axis or direction

Before Merging Todo List:
- [x] clean up code (extract large functions)
- [x] Add proper documentation to the functions
- [ ] Make sure all functionalities are covered by test cases

### CODE REVIEW

**Comment by Lemmih** [comment]
The algorithm for generating a monotone polygon goes roughly like this:

  1. Take a `Vector<T,2>` as input to indicate the monotone direction.
  2. Take a `Vec<Point<T,2>>` as input and check the `len` is at least 3.
  3. Find the extremes (min and max) of the points when sorted in the direction of the vector.
     I'll add a function for comparing two points along a given vector.
  4. Take out the two extremal points from the `Vec`.
  5. Partition the remaining points according to whether they're on the left side or right side
    of the imaginary line between the two extremal points.
    The `Orientation` struct can tell you which side they are on.
  6. Sort the two partitioned sets, one in the direction of the vector and one in the opposite
    direction.
  7. Connect the points, starting from the minimal extreme point, going through the set of points
    that are increasing in the direction of the vector, then to the maximal point, and finally
    down through the points that are decreasing in the direction of the vector.

**Comment by obayomy** [comment]
All the functions are now generic for any direction.
So far the "is_montone" function is randomly tested against the positive case only, and edge case is used for the negative case.
I need to find a way to randomly generate non-monotone polygons.

**Comment by obayomy** [comment]
A nice functionally that can be added is to partition a given polygon into monotone pieces. However, as far as I am concerned this algorithm is more complicated and needs specific data structures, so I am not sure if it fits the current roadmap.

**Comment by Lemmih** [comment]
> A nice functionally that can be added is to partition a given polygon into monotone pieces. However, as far as I am concerned this algorithm is more complicated and needs specific data structures, so I am not sure if it fits the current roadmap.

Yeah, we can tackle that in another PR. It's definitely something we want, though. Triangulating polygons by first breaking them down into monotone pieces is an excellent technique.

**Pull request merged**
